// Comprehensive list of US-listed stocks and ETFs
// Covers S&P 500, major NASDAQ, popular ETFs, and actively traded names
export interface StockInfo {
  ticker: string;
  name: string;
  sector?: string;
}

export const US_STOCKS: StockInfo[] = [
  // Mega-cap tech
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
  { ticker: "NVDA", name: "NVIDIA Corporation", sector: "Technology" },
  { ticker: "GOOGL", name: "Alphabet Inc. (Class A)", sector: "Technology" },
  { ticker: "GOOG", name: "Alphabet Inc. (Class C)", sector: "Technology" },
  { ticker: "META", name: "Meta Platforms Inc.", sector: "Technology" },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { ticker: "ORCL", name: "Oracle Corporation", sector: "Technology" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
  { ticker: "INTC", name: "Intel Corporation", sector: "Technology" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology" },
  { ticker: "TXN", name: "Texas Instruments Inc.", sector: "Technology" },
  { ticker: "AMAT", name: "Applied Materials Inc.", sector: "Technology" },
  { ticker: "MU", name: "Micron Technology Inc.", sector: "Technology" },
  { ticker: "LRCX", name: "Lam Research Corporation", sector: "Technology" },
  { ticker: "KLAC", name: "KLA Corporation", sector: "Technology" },
  { ticker: "MRVL", name: "Marvell Technology Inc.", sector: "Technology" },
  { ticker: "NXPI", name: "NXP Semiconductors NV", sector: "Technology" },
  { ticker: "ADI", name: "Analog Devices Inc.", sector: "Technology" },
  { ticker: "MCHP", name: "Microchip Technology Inc.", sector: "Technology" },
  { ticker: "CDNS", name: "Cadence Design Systems", sector: "Technology" },
  { ticker: "SNPS", name: "Synopsys Inc.", sector: "Technology" },
  { ticker: "CRWD", name: "CrowdStrike Holdings", sector: "Technology" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { ticker: "FTNT", name: "Fortinet Inc.", sector: "Technology" },
  { ticker: "ZS", name: "Zscaler Inc.", sector: "Technology" },
  { ticker: "OKTA", name: "Okta Inc.", sector: "Technology" },
  { ticker: "NET", name: "Cloudflare Inc.", sector: "Technology" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology" },
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Technology" },
  { ticker: "MDB", name: "MongoDB Inc.", sector: "Technology" },
  { ticker: "TEAM", name: "Atlassian Corporation", sector: "Technology" },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { ticker: "ANSS", name: "ANSYS Inc.", sector: "Technology" },
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology" },
  { ticker: "APP", name: "Applovin Corporation", sector: "Technology" },
  { ticker: "DELL", name: "Dell Technologies", sector: "Technology" },
  { ticker: "HPQ", name: "HP Inc.", sector: "Technology" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology" },
  { ticker: "IBM", name: "International Business Machines", sector: "Technology" },
  { ticker: "CSCO", name: "Cisco Systems Inc.", sector: "Technology" },
  { ticker: "ACN", name: "Accenture PLC", sector: "Technology" },
  { ticker: "CTSH", name: "Cognizant Technology Solutions", sector: "Technology" },
  { ticker: "ANET", name: "Arista Networks Inc.", sector: "Technology" },
  { ticker: "GLW", name: "Corning Inc.", sector: "Technology" },
  { ticker: "EPAM", name: "EPAM Systems Inc.", sector: "Technology" },
  { ticker: "PAYC", name: "Paycom Software", sector: "Technology" },
  { ticker: "WDAY", name: "Workday Inc.", sector: "Technology" },
  // AI / Cloud
  { ticker: "MSFT", name: "Microsoft (Azure / Copilot)", sector: "Technology" },
  { ticker: "SOUN", name: "SoundHound AI Inc.", sector: "Technology" },
  { ticker: "AI", name: "C3.ai Inc.", sector: "Technology" },
  { ticker: "BBAI", name: "BigBear.ai Holdings", sector: "Technology" },
  // Semiconductors
  { ticker: "ARM", name: "Arm Holdings PLC", sector: "Technology" },
  { ticker: "SMCI", name: "Super Micro Computer", sector: "Technology" },
  { ticker: "ON", name: "ON Semiconductor Corporation", sector: "Technology" },
  { ticker: "WOLF", name: "Wolfspeed Inc.", sector: "Technology" },
  // Internet / E-commerce
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology" },
  { ticker: "ETSY", name: "Etsy Inc.", sector: "Consumer Discretionary" },
  { ticker: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary" },
  { ticker: "PINS", name: "Pinterest Inc.", sector: "Communication Services" },
  { ticker: "SNAP", name: "Snap Inc.", sector: "Communication Services" },
  { ticker: "TWTR", name: "X Corp (formerly Twitter)", sector: "Communication Services" },
  { ticker: "RDDT", name: "Reddit Inc.", sector: "Communication Services" },
  { ticker: "SPOT", name: "Spotify Technology", sector: "Communication Services" },
  { ticker: "RBLX", name: "Roblox Corporation", sector: "Communication Services" },
  { ticker: "U", name: "Unity Software Inc.", sector: "Communication Services" },
  { ticker: "TTD", name: "The Trade Desk Inc.", sector: "Communication Services" },
  { ticker: "ZG", name: "Zillow Group Inc.", sector: "Real Estate" },
  { ticker: "ABNB", name: "Airbnb Inc.", sector: "Consumer Discretionary" },
  { ticker: "BKNG", name: "Booking Holdings Inc.", sector: "Consumer Discretionary" },
  { ticker: "EXPE", name: "Expedia Group Inc.", sector: "Consumer Discretionary" },
  { ticker: "LYFT", name: "Lyft Inc.", sector: "Consumer Discretionary" },
  { ticker: "UBER", name: "Uber Technologies Inc.", sector: "Consumer Discretionary" },
  // Financials
  { ticker: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials" },
  { ticker: "BAC", name: "Bank of America Corporation", sector: "Financials" },
  { ticker: "WFC", name: "Wells Fargo & Company", sector: "Financials" },
  { ticker: "GS", name: "Goldman Sachs Group Inc.", sector: "Financials" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials" },
  { ticker: "C", name: "Citigroup Inc.", sector: "Financials" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { ticker: "PNC", name: "PNC Financial Services", sector: "Financials" },
  { ticker: "AXP", name: "American Express Company", sector: "Financials" },
  { ticker: "V", name: "Visa Inc.", sector: "Financials" },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Financials" },
  { ticker: "PYPL", name: "PayPal Holdings Inc.", sector: "Financials" },
  { ticker: "SQ", name: "Block Inc. (Square)", sector: "Financials" },
  { ticker: "COIN", name: "Coinbase Global Inc.", sector: "Financials" },
  { ticker: "HOOD", name: "Robinhood Markets Inc.", sector: "Financials" },
  { ticker: "SCHW", name: "Charles Schwab Corporation", sector: "Financials" },
  { ticker: "BLK", name: "BlackRock Inc.", sector: "Financials" },
  { ticker: "BX", name: "Blackstone Inc.", sector: "Financials" },
  { ticker: "KKR", name: "KKR & Co. Inc.", sector: "Financials" },
  { ticker: "APO", name: "Apollo Global Management", sector: "Financials" },
  { ticker: "SPGI", name: "S&P Global Inc.", sector: "Financials" },
  { ticker: "MCO", name: "Moody's Corporation", sector: "Financials" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Financials" },
  { ticker: "CME", name: "CME Group Inc.", sector: "Financials" },
  { ticker: "MSCI", name: "MSCI Inc.", sector: "Financials" },
  // Healthcare
  { ticker: "UNH", name: "UnitedHealth Group Inc.", sector: "Healthcare" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { ticker: "LLY", name: "Eli Lilly and Company", sector: "Healthcare" },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { ticker: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { ticker: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { ticker: "BIIB", name: "Biogen Inc.", sector: "Healthcare" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { ticker: "MRNA", name: "Moderna Inc.", sector: "Healthcare" },
  { ticker: "ISRG", name: "Intuitive Surgical Inc.", sector: "Healthcare" },
  { ticker: "MDT", name: "Medtronic PLC", sector: "Healthcare" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { ticker: "DHR", name: "Danaher Corporation", sector: "Healthcare" },
  { ticker: "SYK", name: "Stryker Corporation", sector: "Healthcare" },
  { ticker: "BSX", name: "Boston Scientific Corporation", sector: "Healthcare" },
  { ticker: "EW", name: "Edwards Lifesciences", sector: "Healthcare" },
  { ticker: "ZBH", name: "Zimmer Biomet Holdings", sector: "Healthcare" },
  { ticker: "CVS", name: "CVS Health Corporation", sector: "Healthcare" },
  { ticker: "CI", name: "Cigna Group", sector: "Healthcare" },
  { ticker: "HCA", name: "HCA Healthcare Inc.", sector: "Healthcare" },
  { ticker: "DXCM", name: "DexCom Inc.", sector: "Healthcare" },
  { ticker: "INCY", name: "Incyte Corporation", sector: "Healthcare" },
  // Consumer
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Staples" },
  { ticker: "COST", name: "Costco Wholesale Corporation", sector: "Consumer Staples" },
  { ticker: "TGT", name: "Target Corporation", sector: "Consumer Discretionary" },
  { ticker: "HD", name: "Home Depot Inc.", sector: "Consumer Discretionary" },
  { ticker: "LOW", name: "Lowe's Companies Inc.", sector: "Consumer Discretionary" },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { ticker: "MCD", name: "McDonald's Corporation", sector: "Consumer Discretionary" },
  { ticker: "SBUX", name: "Starbucks Corporation", sector: "Consumer Discretionary" },
  { ticker: "NKE", name: "NIKE Inc.", sector: "Consumer Discretionary" },
  { ticker: "LULU", name: "lululemon athletica Inc.", sector: "Consumer Discretionary" },
  { ticker: "DG", name: "Dollar General Corporation", sector: "Consumer Discretionary" },
  { ticker: "DLTR", name: "Dollar Tree Inc.", sector: "Consumer Discretionary" },
  { ticker: "TJX", name: "TJX Companies Inc.", sector: "Consumer Discretionary" },
  { ticker: "ROST", name: "Ross Stores Inc.", sector: "Consumer Discretionary" },
  { ticker: "ORLY", name: "O'Reilly Automotive Inc.", sector: "Consumer Discretionary" },
  { ticker: "AZO", name: "AutoZone Inc.", sector: "Consumer Discretionary" },
  { ticker: "BBY", name: "Best Buy Co. Inc.", sector: "Consumer Discretionary" },
  { ticker: "KO", name: "Coca-Cola Company", sector: "Consumer Staples" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
  { ticker: "PG", name: "Procter & Gamble Company", sector: "Consumer Staples" },
  { ticker: "PM", name: "Philip Morris International", sector: "Consumer Staples" },
  { ticker: "MO", name: "Altria Group Inc.", sector: "Consumer Staples" },
  { ticker: "KHC", name: "Kraft Heinz Company", sector: "Consumer Staples" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer Staples" },
  { ticker: "GIS", name: "General Mills Inc.", sector: "Consumer Staples" },
  { ticker: "K", name: "Kellanova", sector: "Consumer Staples" },
  { ticker: "CL", name: "Colgate-Palmolive Company", sector: "Consumer Staples" },
  // Energy
  { ticker: "XOM", name: "Exxon Mobil Corporation", sector: "Energy" },
  { ticker: "CVX", name: "Chevron Corporation", sector: "Energy" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy" },
  { ticker: "EOG", name: "EOG Resources Inc.", sector: "Energy" },
  { ticker: "SLB", name: "SLB (Schlumberger)", sector: "Energy" },
  { ticker: "MPC", name: "Marathon Petroleum Corporation", sector: "Energy" },
  { ticker: "VLO", name: "Valero Energy Corporation", sector: "Energy" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy" },
  { ticker: "PXD", name: "Pioneer Natural Resources", sector: "Energy" },
  { ticker: "OXY", name: "Occidental Petroleum Corporation", sector: "Energy" },
  { ticker: "HAL", name: "Halliburton Company", sector: "Energy" },
  { ticker: "DVN", name: "Devon Energy Corporation", sector: "Energy" },
  // Industrials
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrials" },
  { ticker: "FDX", name: "FedEx Corporation", sector: "Industrials" },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials" },
  { ticker: "RTX", name: "RTX Corporation (Raytheon)", sector: "Industrials" },
  { ticker: "LMT", name: "Lockheed Martin Corporation", sector: "Industrials" },
  { ticker: "NOC", name: "Northrop Grumman Corporation", sector: "Industrials" },
  { ticker: "BA", name: "Boeing Company", sector: "Industrials" },
  { ticker: "GD", name: "General Dynamics Corporation", sector: "Industrials" },
  { ticker: "MMM", name: "3M Company", sector: "Industrials" },
  { ticker: "EMR", name: "Emerson Electric Co.", sector: "Industrials" },
  { ticker: "ETN", name: "Eaton Corporation PLC", sector: "Industrials" },
  { ticker: "PH", name: "Parker-Hannifin Corporation", sector: "Industrials" },
  { ticker: "ROK", name: "Rockwell Automation", sector: "Industrials" },
  { ticker: "ITW", name: "Illinois Tool Works Inc.", sector: "Industrials" },
  { ticker: "GWW", name: "W.W. Grainger Inc.", sector: "Industrials" },
  { ticker: "WM", name: "Waste Management Inc.", sector: "Industrials" },
  { ticker: "RSG", name: "Republic Services Inc.", sector: "Industrials" },
  { ticker: "CTAS", name: "Cintas Corporation", sector: "Industrials" },
  { ticker: "FAST", name: "Fastenal Company", sector: "Industrials" },
  // Utilities / Real Estate
  { ticker: "NEE", name: "NextEra Energy Inc.", sector: "Utilities" },
  { ticker: "DUK", name: "Duke Energy Corporation", sector: "Utilities" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities" },
  { ticker: "D", name: "Dominion Energy Inc.", sector: "Utilities" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities" },
  { ticker: "EXC", name: "Exelon Corporation", sector: "Utilities" },
  { ticker: "AMT", name: "American Tower Corporation", sector: "Real Estate" },
  { ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate" },
  { ticker: "CCI", name: "Crown Castle Inc.", sector: "Real Estate" },
  { ticker: "EQIX", name: "Equinix Inc.", sector: "Real Estate" },
  { ticker: "O", name: "Realty Income Corporation", sector: "Real Estate" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Real Estate" },
  { ticker: "DLR", name: "Digital Realty Trust", sector: "Real Estate" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate" },
  // Materials
  { ticker: "LIN", name: "Linde PLC", sector: "Materials" },
  { ticker: "APD", name: "Air Products and Chemicals", sector: "Materials" },
  { ticker: "SHW", name: "Sherwin-Williams Company", sector: "Materials" },
  { ticker: "FCX", name: "Freeport-McMoRan Inc.", sector: "Materials" },
  { ticker: "NEM", name: "Newmont Corporation", sector: "Materials" },
  { ticker: "NUE", name: "Nucor Corporation", sector: "Materials" },
  { ticker: "VMC", name: "Vulcan Materials Company", sector: "Materials" },
  { ticker: "MLM", name: "Martin Marietta Materials", sector: "Materials" },
  // Communication Services
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { ticker: "DIS", name: "Walt Disney Company", sector: "Communication Services" },
  { ticker: "CMCSA", name: "Comcast Corporation", sector: "Communication Services" },
  { ticker: "T", name: "AT&T Inc.", sector: "Communication Services" },
  { ticker: "VZ", name: "Verizon Communications", sector: "Communication Services" },
  { ticker: "CHTR", name: "Charter Communications", sector: "Communication Services" },
  { ticker: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services" },
  { ticker: "PARA", name: "Paramount Global", sector: "Communication Services" },
  { ticker: "EA", name: "Electronic Arts Inc.", sector: "Communication Services" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Communication Services" },
  { ticker: "MTCH", name: "Match Group Inc.", sector: "Communication Services" },
  { ticker: "IAC", name: "IAC Inc.", sector: "Communication Services" },
  // Finance / Insurance / Warren Buffett
  { ticker: "BRK.A", name: "Berkshire Hathaway (Class A)", sector: "Financials" },
  { ticker: "BRK.B", name: "Berkshire Hathaway (Class B)", sector: "Financials" },
  { ticker: "CB", name: "Chubb Limited", sector: "Financials" },
  { ticker: "MMC", name: "Marsh & McLennan Companies", sector: "Financials" },
  { ticker: "AON", name: "Aon PLC", sector: "Financials" },
  { ticker: "MET", name: "MetLife Inc.", sector: "Financials" },
  { ticker: "PRU", name: "Prudential Financial Inc.", sector: "Financials" },
  { ticker: "AIG", name: "American International Group", sector: "Financials" },
  { ticker: "AFL", name: "Aflac Incorporated", sector: "Financials" },
  { ticker: "TRV", name: "Travelers Companies Inc.", sector: "Financials" },
  { ticker: "HIG", name: "Hartford Financial Services", sector: "Financials" },
  { ticker: "ALL", name: "Allstate Corporation", sector: "Financials" },
  { ticker: "PGR", name: "Progressive Corporation", sector: "Financials" },
  // Popular ETFs
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF" },
  { ticker: "QQQ", name: "Invesco QQQ ETF (NASDAQ-100)" },
  { ticker: "QQQM", name: "Invesco NASDAQ-100 ETF" },
  { ticker: "VGT", name: "Vanguard Information Technology ETF" },
  { ticker: "XLK", name: "Technology Select Sector SPDR" },
  { ticker: "XLF", name: "Financial Select Sector SPDR" },
  { ticker: "XLE", name: "Energy Select Sector SPDR" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR" },
  { ticker: "XLC", name: "Communication Services Select Sector SPDR" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR" },
  { ticker: "SOXX", name: "iShares Semiconductor ETF" },
  { ticker: "SMH", name: "VanEck Semiconductor ETF" },
  { ticker: "ARKK", name: "ARK Innovation ETF" },
  { ticker: "ARKG", name: "ARK Genomic Revolution ETF" },
  { ticker: "GLD", name: "SPDR Gold Shares ETF" },
  { ticker: "SLV", name: "iShares Silver Trust ETF" },
  { ticker: "IAU", name: "iShares Gold Trust ETF" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF" },
  { ticker: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF" },
  { ticker: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond ETF" },
  { ticker: "VNQ", name: "Vanguard Real Estate ETF" },
  { ticker: "SCHD", name: "Schwab US Dividend Equity ETF" },
  { ticker: "VYM", name: "Vanguard High Dividend Yield ETF" },
  { ticker: "DVY", name: "iShares Select Dividend ETF" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF" },
  { ticker: "VB", name: "Vanguard Small-Cap ETF" },
  { ticker: "VO", name: "Vanguard Mid-Cap ETF" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF" },
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF" },
  { ticker: "EFA", name: "iShares MSCI EAFE ETF" },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets ETF" },
  { ticker: "INDA", name: "iShares MSCI India ETF" },
  { ticker: "NDAQ", name: "Nasdaq Inc." },
  // Crypto-adjacent / Trending
  { ticker: "MSTR", name: "MicroStrategy Incorporated", sector: "Technology" },
  { ticker: "MARA", name: "Marathon Digital Holdings", sector: "Financials" },
  { ticker: "RIOT", name: "Riot Platforms Inc.", sector: "Financials" },
  { ticker: "CLSK", name: "CleanSpark Inc.", sector: "Energy" },
  // EV / Clean Energy
  { ticker: "RIVN", name: "Rivian Automotive Inc.", sector: "Consumer Discretionary" },
  { ticker: "LCID", name: "Lucid Group Inc.", sector: "Consumer Discretionary" },
  { ticker: "NIO", name: "NIO Inc.", sector: "Consumer Discretionary" },
  { ticker: "XPEV", name: "XPeng Inc.", sector: "Consumer Discretionary" },
  { ticker: "LI", name: "Li Auto Inc.", sector: "Consumer Discretionary" },
  { ticker: "ENPH", name: "Enphase Energy Inc.", sector: "Technology" },
  { ticker: "SEDG", name: "SolarEdge Technologies", sector: "Technology" },
  { ticker: "FSLR", name: "First Solar Inc.", sector: "Technology" },
  { ticker: "PLUG", name: "Plug Power Inc.", sector: "Industrials" },
  { ticker: "BLNK", name: "Blink Charging Co.", sector: "Consumer Discretionary" },
  // Space / Defense
  { ticker: "SPCE", name: "Virgin Galactic Holdings", sector: "Industrials" },
  { ticker: "RKT", name: "Rocket Companies Inc.", sector: "Financials" },
  { ticker: "KTOS", name: "Kratos Defense & Security", sector: "Industrials" },
  { ticker: "RCAT", name: "Red Cat Holdings Inc.", sector: "Industrials" },
  // More S&P 500
  { ticker: "CB", name: "Chubb Limited", sector: "Financials" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy" },
  { ticker: "SRE", name: "Sempra", sector: "Utilities" },
  { ticker: "PCG", name: "PG&E Corporation", sector: "Utilities" },
  { ticker: "CEG", name: "Constellation Energy", sector: "Utilities" },
  { ticker: "APA", name: "APA Corporation", sector: "Energy" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy" },
  { ticker: "MRO", name: "Marathon Oil Corporation", sector: "Energy" },
  { ticker: "HES", name: "Hess Corporation", sector: "Energy" },
  { ticker: "BKR", name: "Baker Hughes Company", sector: "Energy" },
  { ticker: "NOV", name: "NOV Inc.", sector: "Energy" },
  { ticker: "TRGP", name: "Targa Resources Corp.", sector: "Energy" },
  { ticker: "KMI", name: "Kinder Morgan Inc.", sector: "Energy" },
  { ticker: "WMB", name: "Williams Companies Inc.", sector: "Energy" },
  { ticker: "OKE", name: "ONEOK Inc.", sector: "Energy" },
  { ticker: "ET", name: "Energy Transfer LP", sector: "Energy" },
  { ticker: "EPD", name: "Enterprise Products Partners", sector: "Energy" },
  { ticker: "MMP", name: "Magellan Midstream Partners", sector: "Energy" },
  { ticker: "MTD", name: "Mettler-Toledo International", sector: "Healthcare" },
  { ticker: "A", name: "Agilent Technologies", sector: "Healthcare" },
  { ticker: "IQV", name: "IQVIA Holdings Inc.", sector: "Healthcare" },
  { ticker: "ILMN", name: "Illumina Inc.", sector: "Healthcare" },
  { ticker: "PKI", name: "PerkinElmer Inc.", sector: "Healthcare" },
  { ticker: "WAT", name: "Waters Corporation", sector: "Healthcare" },
  { ticker: "BIO", name: "Bio-Rad Laboratories", sector: "Healthcare" },
  { ticker: "IDXX", name: "IDEXX Laboratories Inc.", sector: "Healthcare" },
  { ticker: "HOLX", name: "Hologic Inc.", sector: "Healthcare" },
  { ticker: "RMD", name: "ResMed Inc.", sector: "Healthcare" },
  { ticker: "MTB", name: "M&T Bank Corporation", sector: "Financials" },
  { ticker: "RF", name: "Regions Financial Corporation", sector: "Financials" },
  { ticker: "CFG", name: "Citizens Financial Group", sector: "Financials" },
  { ticker: "FITB", name: "Fifth Third Bancorp", sector: "Financials" },
  { ticker: "KEY", name: "KeyCorp", sector: "Financials" },
  { ticker: "HBAN", name: "Huntington Bancshares", sector: "Financials" },
  { ticker: "STT", name: "State Street Corporation", sector: "Financials" },
  { ticker: "NTRS", name: "Northern Trust Corporation", sector: "Financials" },
  { ticker: "FI", name: "Fiserv Inc.", sector: "Financials" },
  { ticker: "GPN", name: "Global Payments Inc.", sector: "Financials" },
  { ticker: "FIS", name: "Fidelity National Information Services", sector: "Financials" },
  { ticker: "WEX", name: "WEX Inc.", sector: "Financials" },
  { ticker: "CPAY", name: "Corpay Inc.", sector: "Financials" },
  { ticker: "AFRM", name: "Affirm Holdings Inc.", sector: "Financials" },
  { ticker: "SOFI", name: "SoFi Technologies Inc.", sector: "Financials" },
  { ticker: "UPST", name: "Upstart Holdings Inc.", sector: "Financials" },
  { ticker: "LC", name: "LendingClub Corporation", sector: "Financials" },
  { ticker: "NU", name: "Nu Holdings Ltd.", sector: "Financials" },
  { ticker: "TOST", name: "Toast Inc.", sector: "Technology" },
  { ticker: "BILL", name: "Bill Holdings Inc.", sector: "Technology" },
  { ticker: "HUBS", name: "HubSpot Inc.", sector: "Technology" },
  { ticker: "ZI", name: "ZoomInfo Technologies", sector: "Technology" },
  { ticker: "TWLO", name: "Twilio Inc.", sector: "Technology" },
  { ticker: "PTON", name: "Peloton Interactive Inc.", sector: "Consumer Discretionary" },
  { ticker: "DOCU", name: "DocuSign Inc.", sector: "Technology" },
  { ticker: "BOX", name: "Box Inc.", sector: "Technology" },
  { ticker: "DBX", name: "Dropbox Inc.", sector: "Technology" },
  { ticker: "WK", name: "Workiva Inc.", sector: "Technology" },
  { ticker: "SMAR", name: "Smartsheet Inc.", sector: "Technology" },
  { ticker: "MNDY", name: "monday.com Ltd.", sector: "Technology" },
  { ticker: "GTLB", name: "GitLab Inc.", sector: "Technology" },
  { ticker: "CFLT", name: "Confluent Inc.", sector: "Technology" },
  { ticker: "S", name: "SentinelOne Inc.", sector: "Technology" },
  { ticker: "CYBR", name: "CyberArk Software Ltd.", sector: "Technology" },
  { ticker: "QLYS", name: "Qualys Inc.", sector: "Technology" },
  { ticker: "VRNS", name: "Varonis Systems Inc.", sector: "Technology" },
  { ticker: "TENB", name: "Tenable Holdings Inc.", sector: "Technology" },
  { ticker: "RPM", name: "RPM International Inc.", sector: "Materials" },
  { ticker: "FMC", name: "FMC Corporation", sector: "Materials" },
  { ticker: "CE", name: "Celanese Corporation", sector: "Materials" },
  { ticker: "WLK", name: "Westlake Corporation", sector: "Materials" },
  { ticker: "HII", name: "Huntington Ingalls Industries", sector: "Industrials" },
  { ticker: "L3H", name: "L3Harris Technologies", sector: "Industrials" },
  { ticker: "TXT", name: "Textron Inc.", sector: "Industrials" },
  { ticker: "HWM", name: "Howmet Aerospace Inc.", sector: "Industrials" },
  { ticker: "TDG", name: "TransDigm Group", sector: "Industrials" },
  { ticker: "CARR", name: "Carrier Global Corporation", sector: "Industrials" },
  { ticker: "OTIS", name: "Otis Worldwide Corporation", sector: "Industrials" },
  { ticker: "XYL", name: "Xylem Inc.", sector: "Industrials" },
  { ticker: "IEX", name: "IDEX Corporation", sector: "Industrials" },
  { ticker: "ROP", name: "Roper Technologies Inc.", sector: "Industrials" },
  { ticker: "VRSK", name: "Verisk Analytics Inc.", sector: "Industrials" },
  { ticker: "EXPD", name: "Expeditors International", sector: "Industrials" },
  { ticker: "CHRW", name: "C.H. Robinson Worldwide", sector: "Industrials" },
  { ticker: "JBHT", name: "J.B. Hunt Transport Services", sector: "Industrials" },
  { ticker: "OLD", name: "Old Dominion Freight Line", sector: "Industrials" },
  { ticker: "ODFL", name: "Old Dominion Freight Line", sector: "Industrials" },
  { ticker: "RXO", name: "RXO Inc.", sector: "Industrials" },
  { ticker: "SYY", name: "Sysco Corporation", sector: "Consumer Staples" },
  { ticker: "CAG", name: "Conagra Brands Inc.", sector: "Consumer Staples" },
  { ticker: "HRL", name: "Hormel Foods Corporation", sector: "Consumer Staples" },
  { ticker: "TSN", name: "Tyson Foods Inc.", sector: "Consumer Staples" },
  { ticker: "MKC", name: "McCormick & Company", sector: "Consumer Staples" },
  { ticker: "EL", name: "Estee Lauder Companies", sector: "Consumer Staples" },
  { ticker: "CHD", name: "Church & Dwight Co.", sector: "Consumer Staples" },
  { ticker: "CLX", name: "Clorox Company", sector: "Consumer Staples" },
  { ticker: "KMB", name: "Kimberly-Clark Corporation", sector: "Consumer Staples" },
  { ticker: "AVP", name: "Avon Products Inc.", sector: "Consumer Staples" },
  { ticker: "TAP", name: "Molson Coors Beverage Company", sector: "Consumer Staples" },
  { ticker: "SAM", name: "Boston Beer Company", sector: "Consumer Staples" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer Staples" },
  { ticker: "BF.B", name: "Brown-Forman Corporation", sector: "Consumer Staples" },
  { ticker: "DKNG", name: "DraftKings Inc.", sector: "Consumer Discretionary" },
  { ticker: "MGM", name: "MGM Resorts International", sector: "Consumer Discretionary" },
  { ticker: "WYNN", name: "Wynn Resorts Limited", sector: "Consumer Discretionary" },
  { ticker: "LVS", name: "Las Vegas Sands Corp.", sector: "Consumer Discretionary" },
  { ticker: "PENN", name: "Penn Entertainment Inc.", sector: "Consumer Discretionary" },
  { ticker: "F", name: "Ford Motor Company", sector: "Consumer Discretionary" },
  { ticker: "GM", name: "General Motors Company", sector: "Consumer Discretionary" },
  { ticker: "STLA", name: "Stellantis N.V.", sector: "Consumer Discretionary" },
  { ticker: "TM", name: "Toyota Motor Corporation", sector: "Consumer Discretionary" },
  { ticker: "HMC", name: "Honda Motor Co.", sector: "Consumer Discretionary" },
  { ticker: "HOG", name: "Harley-Davidson Inc.", sector: "Consumer Discretionary" },
  { ticker: "PHM", name: "PulteGroup Inc.", sector: "Consumer Discretionary" },
  { ticker: "DHI", name: "D.R. Horton Inc.", sector: "Consumer Discretionary" },
  { ticker: "LEN", name: "Lennar Corporation", sector: "Consumer Discretionary" },
  { ticker: "TOL", name: "Toll Brothers Inc.", sector: "Consumer Discretionary" },
  { ticker: "NVR", name: "NVR Inc.", sector: "Consumer Discretionary" },
  { ticker: "POOL", name: "Pool Corporation", sector: "Consumer Discretionary" },
  { ticker: "MAS", name: "Masco Corporation", sector: "Consumer Discretionary" },
  { ticker: "LEG", name: "Leggett & Platt Inc.", sector: "Consumer Discretionary" },
];

// Deduplicate by ticker
const seen = new Set<string>();
export const STOCKS_DEDUPED = US_STOCKS.filter((s) => {
  if (seen.has(s.ticker)) return false;
  seen.add(s.ticker);
  return true;
});

export function getStockInfo(ticker: string): StockInfo | undefined {
  const t = ticker.toUpperCase().trim();
  return STOCKS_DEDUPED.find((s) => s.ticker === t);
}

export function searchStocks(query: string, limit = 8): StockInfo[] {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase().trim();
  const results: Array<StockInfo & { score: number }> = [];

  for (const stock of STOCKS_DEDUPED) {
    const tickerLower = stock.ticker.toLowerCase();
    const nameLower = stock.name.toLowerCase();

    let score = 0;
    if (tickerLower === q) score = 100;
    else if (tickerLower.startsWith(q)) score = 80;
    else if (nameLower.startsWith(q)) score = 60;
    else if (tickerLower.includes(q)) score = 40;
    else if (nameLower.includes(q)) score = 20;

    if (score > 0) results.push({ ...stock, score });
  }

  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ score: _s, ...rest }) => rest);
}
